N: 66
alpha: 3
batch_size: 4
beta: 0.05
dataset_name: eeg
device: cuda
eeg_highpass_cutoff: 0.5
eeg_lowpass_cutoff: 50
eeg_target_fs: 100
embedding_dim: 40
enable_layer_norm: true
grid_search: false
horizon_prediction: 12
intermediate_output_channels: 64
k: 2
k_sparsity: 15
learning_rate: 0.001
log_each: 1
log_level: INFO
loss_kind: l1
m: 4
model_kind: MTGNN
n_epoch: 10
nb_iter_per_epoch: 0
normalization_method: zscore
output_dir: saved_models/20260104-182531
p_dropout: 0.3
path_eeg: ../eeg/sub-001_task-Rest_run-01_eeg.set
pipeline_plotting: false
plotting_horizon: false
preprocessing: true
residual_channels: 16
seed: 42
skip_layer_channels: 32
tensorboard_dir: runs
timepoints_input: 100
train_ratio: 0.6
val_batch_size: 16
weight_decay: 0.0001
