N: 137
alpha: 3
batch_size: 4
beta: 0.05
dataset_name: solar
device: cuda
eeg_highpass_cutoff: 50
eeg_target_fs: 100
embedding_dim: 40
enable_layer_norm: true
horizon_prediction: 6
intermediate_output_channels: 64
k: 2
k_sparsity: 20
learning_rate: 0.0001
log_each: 1
log_level: INFO
loss_kind: l1
m: 4
model_kind: MTGNN
move_all_device: true
n_epoch: 10
nb_iter_per_epoch: 0
normalization_method: max
output_dir: saved_models/20260103-195700
p_dropout: 0.3
path_eeg: None
pipeline_plotting: false
plotting_horizon: false
preprocessing: false
residual_channels: 16
seed: 42
skip_layer_channels: 32
tensorboard_dir: runs
timepoints_input: 168
train_ratio: 0.6
val_batch_size: 16
weight_decay: 1.0e-05
