[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multi_time_gnn"
version = "0.1.0"
dependencies = [] 

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["multi_time_gnn"]