N: 137
batch_size: 4
dataset_name: solar
device: cpu
eeg_highpass_cutoff: 50
eeg_target_fs: 100
horizon_prediction: 3
log_each: 1
log_level: INFO
loss_kind: l1
model_kind: AR_global
normalization_method: max
output_dir: saved_models/20260103-230732
path_eeg: None
pipeline_plotting: false
plotting_horizon: false
preprocessing: false
seed: 42
tensorboard_dir: runs
timepoints_input: 168
train_ratio: 0.6
val_batch_size: 16
