N: 66
batch_size: 16
dataset_name: eeg
device: cpu
eeg_highpass_cutoff: 0.5
eeg_lowpass_cutoff: 50
eeg_target_fs: 100
horizon_prediction: 3
log_each: 1
log_level: INFO
loss_kind: l1
model_kind: AR_global
normalization_method: zscore
output_dir: saved_models/20260104-191348
path_eeg: /Users/tommariani/Downloads/eeg/sub-001_task-Rest_run-01_eeg.set
pipeline_plotting: false
plotting_horizon: false
preprocessing: true
seed: 42
tensorboard_dir: runs
timepoints_input: 150
train_ratio: 0.6
val_batch_size: 64
